spring.application.name=bff-gateway


server.port=9090
# =========================
# ROUTES
# =========================

spring.cloud.gateway.server.webflux.routes[0].id=register-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:9091
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/register/**

spring.cloud.gateway.server.webflux.routes[1].id=login-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:9092
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/login/**

# =========================
# ACTUATOR
# =========================

management.endpoints.web.exposure.include=*

# =========================
# LOGGING
# =========================

logging.level.org.springframework.cloud.gateway=DEBUG

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.add-to-simple-url-handler-mapping=true
